catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - apps/*
  - locals/*

overrides:
  is-arguments: npm:@nolyfill/is-arguments@^1.0.44
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  is-generator-function: npm:@nolyfill/is-generator-function@^1.0.44
  is-typed-array: npm:@nolyfill/is-typed-array@^1.0.44
  isarray: npm:@nolyfill/isarray@^1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  string.prototype.codepointat: npm:@nolyfill/string.prototype.codepointat@^1.0.44
  which-typed-array: npm:@nolyfill/which-typed-array@^1.0.44
catalog:
  '@ai-sdk/anthropic': ^2.0.53
  '@ai-sdk/google': ^2.0.44
  '@ai-sdk/groq': ^2.0.32
  '@ai-sdk/openai': ^2.0.77
  '@ai-sdk/provider': ^2.0.0
  '@ai-sdk/vue': ^2.0.106
  '@antfu/eslint-config': ^6.4.2
  '@aws-sdk/client-dynamodb': ^3.943.0
  '@aws-sdk/client-s3': ^3.943.0
  '@aws-sdk/lib-dynamodb': ^3.943.0
  '@convex-dev/rate-limiter': ^0.3.0
  '@convex-dev/sharded-counter': ^0.2.0
  '@dotenvx/dotenvx': 1.51.1
  '@hono/standard-validator': ^0.2.0
  '@hono/zod-validator': ^0.7.5
  '@namesmt/utils': ^0.5.18
  '@namesmt/vue-query-nuxt': ^0.3.7
  '@nuxt/eslint': ^1.11.0
  '@nuxt/image': ^2.0.0
  '@nuxtjs/color-mode': ^4.0.0
  '@nuxtjs/i18n': ^10.2.1
  '@nuxtjs/mdc': 0.19.1
  '@nuxtjs/seo': ^3.2.2
  '@openrouter/ai-sdk-provider': ^1.4.0
  '@scalar/hono-api-reference': ^0.9.26
  '@tanstack/query-persist-client-core': ^5.91.11
  '@tanstack/vue-query': ^5.92.1
  '@types/aws-lambda': ^8.10.159
  '@types/node': ^24.10.1
  '@unocss/eslint-plugin': ^66.5.10
  '@unocss/nuxt': ^66.5.10
  '@vitest/coverage-v8': ^4.0.15
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^14.1.0
  '@vueuse/integrations': ^14.1.0
  '@vueuse/motion': ^3.0.3
  '@vueuse/nuxt': ^14.1.0
  '@vueuse/router': ^14.1.0
  '@workos-inc/node': ^7.77.0
  ai: ^5.0.106
  arktype: ^2.1.28
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  convex: ^1.30.0
  convex-helpers: ^0.1.106
  convex-nuxt: ^0.1.5
  dayjs: ^1.11.19
  destr: ^2.0.5
  dotenv: ^16.6.1
  embla-carousel: ^8.6.0
  embla-carousel-vue: ^8.6.0
  eslint: ^9.39.1
  fetch-result-please: ^0.2.0
  grammy: ^1.38.4
  h3-proxy: ^1.13.0
  hono: ^4.10.7
  hono-adapter-aws-lambda: ^1.3.3
  hono-cookie-state: ^0.1.4
  hono-openapi: ^1.1.1
  idb-keyval: ^6.2.2
  kontroll: ^1.1.1
  lenis: ^1.3.15
  lint-staged: ^16.2.7
  lucide-vue-next: ^0.555.0
  nuxt: ^4.2.1
  nuxt-booster: ^3.3.2
  nuxt-llms: ^0.1.3
  nuxt-svgo: 4.2.6
  ohash: ^2.0.11
  pathe: ^2.0.3
  petite-vue-i18n: ^11.2.2
  reka-ui: ^2.6.1
  sass: ^1.94.2
  shadcn-nuxt: ^2.4.1
  simple-git-hooks: ^2.13.1
  spreadsheet-i18n: ^0.3.8
  srvx: ^0.9.7
  sst: ^3.17.24
  std-env: ^3.10.0
  tailwind-merge: ^3.4.0
  tsdown: ^0.17.0
  tsx: ^4.21.0
  turbo: ^2.6.3
  type-fest: ^5.3.0
  typescript: ^5.9.3
  ufo: ^1.6.1
  unocss: ^66.5.10
  unocss-preset-animations: ^1.3.0
  unocss-preset-shadcn: ^1.0.1
  vite-plugin-optimize-exclude: ^0.0.1
  vitest: ^4.0.15
  vue: ^3.5.25
  vue-router: ^4.6.3
  vue-tsc: ^3.1.5
  zod: ^4.1.13
ignoredBuiltDependencies:
  - '@namesmt/vue-query-nuxt'
  - aws-sdk

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
